--- 
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  labels: 
    app: producer-app
  name: producer-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: producer-app
  template: 
    metadata: 
      labels: 
        app: producer-app
    spec: 
      containers: 
        - name: producer-app
          image: producer:latest
          imagePullPolicy: Never
          ports: 
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: producer-app
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32768
  selector:
    app: producer-app